### ISSUE TITLE
Rare freezes after choosing the winner of a round

### ISSUE THREAD

**Issue by fgubler** [JordanPawlett/cards-against-formality#3]
In rare cases, the game "freezes" after the Czar has chosen a winner. 
If that happens, the game needs to be restarted.

With freezing I mean that the next round is not started. This is experienced equally by all players in the room.
With rare I mean maybe once every 50-100 rounds => it is not such a big deal (but of course depressing when it happens).

Unfortunately, I forgot to make a screenshot of the browser-log when it happened, sorry. I will try to remember doing it next time.

**Comment by JordanPawlett** [comment]
When did you last see this issue occur? I say this, as a release was made the other day.
In it was a bugfix for where the game runs out of unique cards to play, meaning it is unable to serve everyone cards for the next round. This could cause the game to freeze after winner selection. Maybe this could have fixed the issue?

**Comment by fgubler** [comment]
I saw it once yesterday (sunday). But only once in about 50 rounds.
I also played on saturday but then it never happened.
Sorry that I cannot be more precise

**Comment by bengm** [comment]
We had a similar issue last night. It froze. The card czar attempted to hit 'submit' for the winning choice a few times; then received the red-background "!" icon; at some point the game finally proceeded and the multiple submits resulted in multiple points for the picked winner for that round.

This happened about 2-3 times in the course of play. It was new years eve, presumably a high-load evening, so that may have something to do with it.
